
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0aa2b43bbf27899b18fc025f427e1d9c89c1c608",
 "version": "0+untagged.2.g0aa2b43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
